GET  http://localhost:8080/v1/healthz HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/v1/users HTTP/1.1
content-type: application/json

{
    "name": "Johnny Sins"
}

### 
GET http://localhost:8080/v1/users HTTP/1.1
content-type: application/json
Authorization: ApiKey 17917ddf3a93544f917c53aa05885dd75711df9d38650829c24241538003d039

### 

POST http://localhost:8080/v1/feeds HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

{
    "name": "Wagslane blogs",
    "url": "https://www.wagslane.dev/index.xml"
}

### 

GET http://localhost:8080/v1/feeds HTTP/1.1
content-type: application/json

### 

POST http://localhost:8080/v1/feed_follows HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

{
    "feed_id": "7d9a2d5d-1193-49fb-a841-2cc5bda80c66",
    "user_id": "757a8984-da5d-4ef8-bf8e-ac855e8ecf47"
}

### 

GET http://localhost:8080/v1/feed_follows HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

###

DELETE http://localhost:8080/v1/feed_follows/66a9e0b4-a0f7-46c9-912f-306bc91f03e9 HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

###

GET http://localhost:8080/v1/posts?limit=10&page=39 HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f
