### GET: /healthz
GET  http://localhost:8080/v1/healthz HTTP/1.1
content-type: application/json

### GET: /users
GET http://localhost:8080/v1/users HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

### POST: /users
POST http://localhost:8080/v1/users HTTP/1.1
content-type: application/json

{
    "name": "Huy"
}

### GET: /feeds
GET http://localhost:8080/v1/feeds?limit=3&page=1 HTTP/1.1
content-type: application/json

### POST: /feeds 
POST http://localhost:8080/v1/feeds HTTP/1.1
content-type: application/json
Authorization: ApiKey 17917ddf3a93544f917c53aa05885dd75711df9d38650829c24241538003d039

{
    "name": "Wagslane blog",
    "url": "https://www.wagslane.dev/index.xml"
}

### GET: /feed_follows
GET http://localhost:8080/v1/feed_follows HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

### POST: /feed_follows
POST http://localhost:8080/v1/feed_follows HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

{
    "feed_id": "31b23de0-37cf-4479-b4c8-8576ff294603"
}

### DELETE: /feed_follows
DELETE http://localhost:8080/v1/feed_follows/cde222f5-08f8-4cc0-89b4-0eb91c77a283 HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

### GET: /posts
GET http://localhost:8080/v1/posts?limit=1&page=10 HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f
