GET  http://localhost:8080/v1/healthz HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/v1/users HTTP/1.1
content-type: application/json

{
    "name": "Tom"
}

### 
GET http://localhost:8080/v1/users HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

### 

POST http://localhost:8080/v1/feeds HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

{
    "name": "Wagslane blogs",
    "url": "https://www.wagslane.dev/index.xml"
}

### 

GET http://localhost:8080/v1/feeds HTTP/1.1
content-type: application/json

### 

POST http://localhost:8080/v1/feed_follows HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

{
    "feed_id": "31b23de0-37cf-4479-b4c8-8576ff294603",
    "user_id": "757a8984-da5d-4ef8-bf8e-ac855e8ecf47"
}

### 

GET http://localhost:8080/v1/feed_follows HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f

###

DELETE http://localhost:8080/v1/feed_follows/152929cd-b5e7-43ae-b6ea-47c0126b6054 HTTP/1.1
content-type: application/json
Authorization: ApiKey 3c6b5bac369f498ace97215aa11284c4ee495fefb52d27c2bbb1b38e2cb4342f